"""test column

Revision ID: d59263ebf7f8
Revises: 6f293d6a24fc
Create Date: 2026-04-30 21:45:26.361740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd59263ebf7f8'
down_revision = '6f293d6a24fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test', sa.String(length=100), nullable=True))
        batch_op.drop_column('test_1')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test_1', sa.VARCHAR(length=100), server_default=sa.text("'test'"), nullable=True))
        batch_op.drop_column('test')

    # ### end Alembic commands ###
